# context output structure:
# ------------------
# Key         | Type        | Description
# ------------|-------------|---------------------------------------------------------------
# docId       | str         | Indicates the docId document (default is test123456)
# file_type   | str         | Indicates the format of the original document (e.g., "pdf")
# summary     | str         | A brief description of the document's contents generated by an LLM
# source      | str         | Full path to the original document file
# chunks      | list[dict]  | A list of chunked document segments, each with semantic data (PDF/DOCX)
# embeddings  | str         | Now this returns the name of the embedding model (PDF/DOCX)
# image_data  | bytes       | A raw binary representation of the image file (PNG/JPG)
# content     | str         | Preprocessed text extract from the csv (CSV)
# response_time| str         | Document processing response time in seconds


import app.services.document_processing
from pathlib import Path

# test path can be changed here 
file_path = Path(r"C:\Users\600002608\Git\medpro-data-ai-gpt\genai\app\testdocs\test.pdf")

context = app.services.document_processing.process_file(file_path)   

if context:
    file_type = context.get("file_type")
    print ("\n File Type: \n", file_type)
    summary = context.get("summary")  # Works for all file types
    print ("\n Summary: \n", summary)
    if file_type in [".pdf", ".docx"]:
        chunks = context.get("vectors")
    elif file_type == ".csv":
        content = context.get("content")
    elif file_type in [".jpg", ".jpeg", ".png"]:
        image_data = context.get("image_data")

# Test output debugging
print ("\n Output Structure: context")
for k, v in context.items():
    print(f"{k}: {str(v)[:500]}{'...' if len(str(v)) > 500 else ''}")

'''
# Debugging for pdf/docx only
print ("\n Output Structure: context['chunks']")
for i, chunks in enumerate(context["chunks"]):
    print(f"\n--- Vector {i + 1} ---")
    for k, v in vector.items():
        print(f"{k}: {str(v)[:150]}{'...' if len(str(v)) > 150 else ''}")
'''

# Example: context["chunks"][0] for pdf/docx
# -------------------------------
# Key         | Type         | Description
# ------------|--------------|---------------------------------------------------------------
# content     | str          | Raw or cleaned text from the document chunk
# embedding   | list[float]  | A high-dimensional vector used for semantic search, similarity, or clustering
# file_type   | str          | Format of the original document (repeated for traceability)
# source      | str          | File path + chunk index (e.g., "/path.pdf chunk 1/1")
# id          | int          | Unique identifier for the chunk (e.g., 0)

